[2025-02-01T09:32:43.766+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T09:32:43.788+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sora_etl_pipeline.process_float_data manual__2025-02-01T09:31:56.599018+00:00 [queued]>
[2025-02-01T09:32:43.800+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sora_etl_pipeline.process_float_data manual__2025-02-01T09:31:56.599018+00:00 [queued]>
[2025-02-01T09:32:43.802+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-01T09:32:43.822+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_float_data> on 2025-02-01 09:31:56.599018+00:00
[2025-02-01T09:32:43.830+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T09:32:43.833+0000] {standard_task_runner.py:72} INFO - Started process 164 to run task
[2025-02-01T09:32:43.833+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sora_etl_pipeline', 'process_float_data', 'manual__2025-02-01T09:31:56.599018+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp52uz9ps3']
[2025-02-01T09:32:43.838+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask process_float_data
[2025-02-01T09:32:43.913+0000] {task_command.py:467} INFO - Running <TaskInstance: sora_etl_pipeline.process_float_data manual__2025-02-01T09:31:56.599018+00:00 [running]> on host 3356813209df
[2025-02-01T09:32:44.034+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sora_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_float_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T09:31:56.599018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T09:31:56.599018+00:00'
[2025-02-01T09:32:44.036+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T09:32:44.064+0000] {_universal.py:509} INFO - Request URL: 'https://***datalakestaging.dfs.core.windows.net/sora-container?resource=REDACTED&directory=REDACTED&recursive=REDACTED&sv=REDACTED&st=REDACTED&se=REDACTED&sr=REDACTED&sp=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/json'
    'User-Agent': 'azsdk-python-storage-dfs/12.18.0 Python/3.12.8 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7d5f4ee2-e07f-11ef-9ab8-0242ac150004'
No body was attached to the request
[2025-02-01T09:32:45.025+0000] {_universal.py:545} INFO - Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;charset=utf-8'
    'Server': 'Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1c904e59-b01f-004f-418c-7416df000000'
    'x-ms-version': 'REDACTED'
    'x-ms-client-request-id': '7d5f4ee2-e07f-11ef-9ab8-0242ac150004'
    'Date': 'Sat, 01 Feb 2025 09:32:44 GMT'
[2025-02-01T09:32:46.375+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:32:46.842+0000] {_universal.py:509} INFO - Request URL: 'https://***datalakestaging.blob.core.windows.net/sora-container/Float/Float_allocations.csv?sv=REDACTED&st=REDACTED&se=REDACTED&sr=REDACTED&sp=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-dfs/12.18.0 Python/3.12.8 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7f072cd8-e07f-11ef-9ab8-0242ac150004'
No body was attached to the request
[2025-02-01T09:32:48.177+0000] {_universal.py:545} INFO - Response status: 206
Response headers:
    'Content-Length': '1288'
    'Content-Type': 'application/vnd.ms-excel'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Fri, 31 Jan 2025 21:08:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD423B6DDEC540"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '46dce002-701e-0032-0f8c-7467fc000000'
    'x-ms-client-request-id': '7f072cd8-e07f-11ef-9ab8-0242ac150004'
    'x-ms-version': 'REDACTED'
    'x-ms-resource-type': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'x-ms-owner': 'REDACTED'
    'x-ms-group': 'REDACTED'
    'x-ms-permissions': 'REDACTED'
    'x-ms-acl': 'REDACTED'
    'Date': 'Sat, 01 Feb 2025 09:32:47 GMT'
[2025-02-01T09:32:49.302+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:32:50.837+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:32:52.687+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:54.318+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:56.161+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:57.777+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:59.336+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:33:00.975+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:33:02.619+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:33:04.755+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:33:06.603+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:33:09.713+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:33:13.652+0000] {etl_dag.py:76} INFO - Float ETL process completed successfully
[2025-02-01T09:33:13.653+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-01T09:33:13.670+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T09:33:13.671+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sora_etl_pipeline, task_id=process_float_data, run_id=manual__2025-02-01T09:31:56.599018+00:00, execution_date=20250201T093156, start_date=20250201T093243, end_date=20250201T093313
[2025-02-01T09:33:13.715+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T09:33:13.738+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T09:33:13.742+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
