[2025-02-01T09:32:01.653+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T09:32:01.673+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sora_etl_pipeline.process_clickup_data manual__2025-02-01T09:31:56.599018+00:00 [queued]>
[2025-02-01T09:32:01.684+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sora_etl_pipeline.process_clickup_data manual__2025-02-01T09:31:56.599018+00:00 [queued]>
[2025-02-01T09:32:01.685+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-01T09:32:01.703+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_clickup_data> on 2025-02-01 09:31:56.599018+00:00
[2025-02-01T09:32:01.710+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=144) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T09:32:01.713+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2025-02-01T09:32:01.713+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sora_etl_pipeline', 'process_clickup_data', 'manual__2025-02-01T09:31:56.599018+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpf5vkacaw']
[2025-02-01T09:32:01.717+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask process_clickup_data
[2025-02-01T09:32:01.784+0000] {task_command.py:467} INFO - Running <TaskInstance: sora_etl_pipeline.process_clickup_data manual__2025-02-01T09:31:56.599018+00:00 [running]> on host 3356813209df
[2025-02-01T09:32:01.901+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sora_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_clickup_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T09:31:56.599018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T09:31:56.599018+00:00'
[2025-02-01T09:32:01.903+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T09:32:01.960+0000] {_universal.py:509} INFO - Request URL: 'https://***datalakestaging.dfs.core.windows.net/sora-container?resource=REDACTED&directory=REDACTED&recursive=REDACTED&sv=REDACTED&st=REDACTED&se=REDACTED&sr=REDACTED&sp=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/json'
    'User-Agent': 'azsdk-python-storage-dfs/12.18.0 Python/3.12.8 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6446b378-e07f-11ef-8178-0242ac150004'
No body was attached to the request
[2025-02-01T09:32:03.329+0000] {_universal.py:545} INFO - Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;charset=utf-8'
    'Server': 'Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'eb58402e-401f-004b-268c-749bd8000000'
    'x-ms-version': 'REDACTED'
    'x-ms-client-request-id': '6446b378-e07f-11ef-8178-0242ac150004'
    'Date': 'Sat, 01 Feb 2025 09:32:02 GMT'
[2025-02-01T09:32:04.866+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:32:05.476+0000] {_universal.py:509} INFO - Request URL: 'https://***datalakestaging.blob.core.windows.net/sora-container/Clickup/clickup.csv?sv=REDACTED&st=REDACTED&se=REDACTED&sr=REDACTED&sp=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-dfs/12.18.0 Python/3.12.8 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '665f3e0a-e07f-11ef-8178-0242ac150004'
No body was attached to the request
[2025-02-01T09:32:07.132+0000] {_universal.py:545} INFO - Response status: 206
Response headers:
    'Content-Length': '45861'
    'Content-Type': 'application/vnd.ms-excel'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Fri, 31 Jan 2025 21:08:29 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD423B69443B30"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f2a295eb-a01e-006c-5a8c-748c1c000000'
    'x-ms-client-request-id': '665f3e0a-e07f-11ef-8178-0242ac150004'
    'x-ms-version': 'REDACTED'
    'x-ms-resource-type': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'x-ms-owner': 'REDACTED'
    'x-ms-group': 'REDACTED'
    'x-ms-permissions': 'REDACTED'
    'x-ms-acl': 'REDACTED'
    'Date': 'Sat, 01 Feb 2025 09:32:06 GMT'
[2025-02-01T09:32:09.261+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:32:13.049+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:32:15.002+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:19.192+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:20.677+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:24.348+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:26.055+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:29.832+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:31.386+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:36.397+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:32:42.173+0000] {etl_dag.py:49} INFO - ClickUp ETL process completed successfully
[2025-02-01T09:32:42.175+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-01T09:32:42.185+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T09:32:42.186+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sora_etl_pipeline, task_id=process_clickup_data, run_id=manual__2025-02-01T09:31:56.599018+00:00, execution_date=20250201T093156, start_date=20250201T093201, end_date=20250201T093242
[2025-02-01T09:32:42.220+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T09:32:42.238+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-01T09:32:42.241+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
