[2025-02-01T09:11:55.606+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T09:11:55.640+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sora_etl_pipeline.process_clickup_data manual__2025-02-01T09:05:23.081380+00:00 [queued]>
[2025-02-01T09:11:55.654+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sora_etl_pipeline.process_clickup_data manual__2025-02-01T09:05:23.081380+00:00 [queued]>
[2025-02-01T09:11:55.655+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 4
[2025-02-01T09:11:55.677+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_clickup_data> on 2025-02-01 09:05:23.081380+00:00
[2025-02-01T09:11:55.685+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T09:11:55.688+0000] {standard_task_runner.py:72} INFO - Started process 205 to run task
[2025-02-01T09:11:55.689+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sora_etl_pipeline', 'process_clickup_data', 'manual__2025-02-01T09:05:23.081380+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpt0slkezq']
[2025-02-01T09:11:55.692+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask process_clickup_data
[2025-02-01T09:11:55.767+0000] {task_command.py:467} INFO - Running <TaskInstance: sora_etl_pipeline.process_clickup_data manual__2025-02-01T09:05:23.081380+00:00 [running]> on host a76c925adcd3
[2025-02-01T09:11:55.902+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sora_etl_pipeline' AIRFLOW_CTX_TASK_ID='process_clickup_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T09:05:23.081380+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T09:05:23.081380+00:00'
[2025-02-01T09:11:55.904+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T09:11:55.935+0000] {_universal.py:509} INFO - Request URL: 'https://***datalakestaging.dfs.core.windows.net/sora-container?resource=REDACTED&directory=REDACTED&recursive=REDACTED&sv=REDACTED&st=REDACTED&se=REDACTED&sr=REDACTED&sp=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/json'
    'User-Agent': 'azsdk-python-storage-dfs/12.18.0 Python/3.12.8 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '956ddf88-e07c-11ef-b57d-0242ac150006'
No body was attached to the request
[2025-02-01T09:11:57.391+0000] {_universal.py:545} INFO - Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;charset=utf-8'
    'Server': 'Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '021b29fb-b01f-002d-6589-74d4f8000000'
    'x-ms-version': 'REDACTED'
    'x-ms-client-request-id': '956ddf88-e07c-11ef-b57d-0242ac150006'
    'Date': 'Sat, 01 Feb 2025 09:11:56 GMT'
[2025-02-01T09:11:59.397+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:11:59.895+0000] {_universal.py:509} INFO - Request URL: 'https://***datalakestaging.blob.core.windows.net/sora-container/Clickup/clickup.csv?sv=REDACTED&st=REDACTED&se=REDACTED&sr=REDACTED&sp=REDACTED&sig=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-dfs/12.18.0 Python/3.12.8 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '97ca30ba-e07c-11ef-b57d-0242ac150006'
No body was attached to the request
[2025-02-01T09:12:02.014+0000] {_universal.py:545} INFO - Response status: 206
Response headers:
    'Content-Length': '45861'
    'Content-Type': 'application/vnd.ms-excel'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Fri, 31 Jan 2025 21:08:29 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD423B69443B30"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9664a1c2-201e-004d-6489-74a867000000'
    'x-ms-client-request-id': '97ca30ba-e07c-11ef-b57d-0242ac150006'
    'x-ms-version': 'REDACTED'
    'x-ms-resource-type': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'x-ms-owner': 'REDACTED'
    'x-ms-group': 'REDACTED'
    'x-ms-permissions': 'REDACTED'
    'x-ms-acl': 'REDACTED'
    'Date': 'Sat, 01 Feb 2025 09:12:01 GMT'
[2025-02-01T09:12:03.161+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:12:07.564+0000] {warnings.py:112} WARNING - /opt/***/dags/utils.py:118: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

[2025-02-01T09:12:09.686+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:12:14.447+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:12:16.661+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:12:20.739+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:12:22.584+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:12:26.334+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:12:27.782+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:74: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_dim = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:12:32.684+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_process.py:107: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mapping = pd.read_sql(query, self.db_client.get_connection())

[2025-02-01T09:12:38.330+0000] {etl_dag.py:49} INFO - ClickUp ETL process completed successfully
[2025-02-01T09:12:38.333+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-01T09:12:38.354+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T09:12:38.355+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sora_etl_pipeline, task_id=process_clickup_data, run_id=manual__2025-02-01T09:05:23.081380+00:00, execution_date=20250201T090523, start_date=20250201T091155, end_date=20250201T091238
[2025-02-01T09:12:38.406+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T09:12:38.439+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-01T09:12:38.443+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
